version: '3.8'

services:
  blockscout-frontend:
    image: flashbots/blockscout-frontend:1.17.0
    pull_policy: always
    restart: always
    container_name: 'blockscout-frontend'
    env_file:
      -  ../envs/common-frontend.env
